
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author fernando
 */
public class Principal extends javax.swing.JFrame {

    private Timer timer;
    private int tempo;

    public Principal() {
        initComponents();

        tempo = 0;

        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tempo++;
                campoTempo.setText(
                        String.format(
                                "%3d:%2d",
                                (tempo / 60),
                                (tempo % 60)).replace(' ', '0')
                );
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        botaoIniciar = new javax.swing.JToggleButton();
        campoTempo = new javax.swing.JTextField();
        botaoZerar = new javax.swing.JButton();
        botaoVolta = new javax.swing.JButton();
        botaoRemover = new javax.swing.JButton();
        botaoLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTempos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        botaoIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iniciar.png"))); // NOI18N
        botaoIniciar.setFocusable(false);
        botaoIniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoIniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iniciar.png"))); // NOI18N
        botaoIniciar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/parar.png"))); // NOI18N
        botaoIniciar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/parar.png"))); // NOI18N
        botaoIniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoIniciar);

        campoTempo.setEditable(false);
        campoTempo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        campoTempo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        campoTempo.setText("000:00");
        jToolBar1.add(campoTempo);

        botaoZerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zerar.png"))); // NOI18N
        botaoZerar.setFocusable(false);
        botaoZerar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoZerar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botaoZerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoZerarActionPerformed(evt);
            }
        });
        jToolBar1.add(botaoZerar);

        botaoVolta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/volta.png"))); // NOI18N
        botaoVolta.setFocusable(false);
        botaoVolta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoVolta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(botaoVolta);

        botaoRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        botaoRemover.setFocusable(false);
        botaoRemover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoRemover.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(botaoRemover);

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/removertodos.png"))); // NOI18N
        botaoLimpar.setFocusable(false);
        botaoLimpar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botaoLimpar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(botaoLimpar);

        jScrollPane1.setViewportView(listaTempos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        if (botaoIniciar.isSelected()) {
            timer.start();
        } else {
            timer.stop();
        }
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void botaoZerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoZerarActionPerformed
        tempo = 0;
        campoTempo.setText(
                String.format(
                        "%3d:%2d",
                        (tempo / 60),
                        (tempo % 60)).replace(' ', '0')
        );        
    }//GEN-LAST:event_botaoZerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botaoIniciar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoRemover;
    private javax.swing.JButton botaoVolta;
    private javax.swing.JButton botaoZerar;
    private javax.swing.JTextField campoTempo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JList<String> listaTempos;
    // End of variables declaration//GEN-END:variables
}
